### ISSUE TITLE
Update of Wiki link

### ISSUE THREAD

**Issue by fa201** [LibreCAD/website#10]
In the main page, the link to Dokuwiki is not updated (_Build from source_ section).
Recommended link would be https://librecad.readthedocs.io/en/latest/appx/build.html

**Comment by nicorikken** [comment]
The manual is not the wiki, right? To get to the manual, one can open the wiki and follow the link to the [manual page](https://dokuwiki.librecad.org/doku.php/usage:manuals). I think it would make sense to link the manual from the frontpage directly, but I think the wiki link is correct.

**Comment by lordofbikes** [comment]
fixed, many thanks!
