### ISSUE TITLE
Are the PPA's still worth mentioning?

### ISSUE THREAD

**Issue by nicorikken** [LibreCAD/website#12]
_Thanks for your work on LibreCAD! I've finally got a reason to start using it and so far I like it. Also, the documentation is very good._

I just installed LibreCAD on Debian Bullseye, resulting in version 2.1.3. I'd like to use the multiple-pages feature, which seems to be introduced in a more recent version. Looking for ways to install a newer version, I found the suggestion of the [PPA's](https://launchpad.net/~librecad-dev) on the website. Looking at the published packages, they are only available for older versions of Ubuntu and not many versions are provided.

I get that the PPA is still around, but with the latest release being from june 2018, I think it shouldn't be recommended on the website as an install option. I think it would be best to remove the link, or make it more explicit that it hasn't been updated in a while.

Perhaps for the project it might be worth looking into other release methods for distributing newer versions outside of distribution repositories, like Flatpak, Snap or AppImage.

**Comment by nicorikken** [comment]
I just noticed the open issues and initial workfor AppImage and Flatpak support at the LibreCAD repo.

**Comment by lordofbikes** [comment]
The only place I could find the PPA was the manual, where I just removed it.
The old wiki is read only and marked as outdated, I can't change it without some efforts.
